### ISSUE TITLE
GMStepper for iOS 7

### ISSUE THREAD

**Issue by zacwolff** [gmertk/GMStepper#14]
Hey Günay, thank you for sharing this. It's really impressive work you've done. I'm interested in including your stepper in a project I am currently working on. 

Is it possible you would in the nearest future patch this up for iOS 7? Thank you once again.

**Comment by gmertk** [comment]
Hi Zac, no promises but I can do it some time. Feel free to send pull requests :)

**Comment by zacwolff** [comment]
Thanks man. I appreciate your work.
