### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by Legoless** [gmertk/GMStepper#25]
I have a test version ready on: https://github.com/Legoless/GMStepper/tree/Swift3

But would not recommend merging into master, so can you maybe create another branch and I will submit a PR.

**Comment by gmertk** [comment]
Hi @Legoless sorry for the late reply. And thank you! 

I created the branch. Will be waiting for your PR. https://github.com/gmertk/GMStepper/tree/swift3

Cheers!

**Comment by lfarah** [comment]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄
