### ISSUE TITLE
Stepper value changed from 1

### ISSUE THREAD

**Issue by ibhavin** [gmertk/GMStepper#30]
I hace setup `GMStepper` in my `UITableViewCell`. In `cellForRowAt indexPath` method I am setting its textlable value like this:
`cell.stepper.label.text = String(receive_Cart[indexPath.row].quantity)`
value is displaying correctly.

But when I changed its value by **+** or **-** it is not changing relative to value which I set in `cellForRowAt indexPath`.

Example: The stepper label is set to **3**. I have press **+** it should display **4** but it is displaying **2**

I have made a delegate of cell and function for stepper:
```
func stepperValueChanged(cell: CartCell) {

    }
```

**Comment by ibhavin** [comment]
Can we know which button pressed plus button or minus button?

**Comment by moderateepheezy** [comment]
@ibhavin how did you solve the issue of knowing which button pressed plus button or minus button?
